### ISSUE TITLE
USGS Import Script

### ISSUE THREAD

**Issue by BrettBoisjolie** [dancrocker/DCR-WIT#5]
Following IT new computer installation, the Quabbin USGS daily import is failing with this error message:

> # Fetch the Daily USGS Data
> df_USGS_Daily <- readNWISdv(siteNo, pCode, start_date, end_date, statCd=c('00003', '00002','00001','00006')) %>%
+   renameNWISColumn

s() %>%
+   select(-1)
Error in inherits(x, c("xml_node", "xml_document", "xml_nodeset")) : 
  no applicable method for 'http_error' applied to an object of class "c('simpleError', 'error', 'condition')"

**Comment by dancrocker** [comment]
Issue resolved by IT. No changed to code required.
